language: python

python:

  - "3.6"
  
install:
  - "pip install pylint"
  
script:
  - python -m unittest discover

after_success:
  - pylint --output-format=html pylint_server > /tmp/pylint-report.html
  - curl -v -m 120 -X POST -F travis-job-id=$TRAVIS_JOB_ID -F pylint-report=@/tmp/pylint-report.html https://63.33.197.197:80/reports
