language: python

python:

  - "3.6"
  
install:
  - "pip install pylint"
  - "pip install coverage"
  - "pip install nose2"
  
script:
  - coverage run -m nose2

after_success:
  - pylint --output-format=parseable no_days_christmas > /tmp/pylint-report.html
  - coverage report -m
  - coverage report -m > /tmp/coverage.html
  - curl -v -m 120 -X POST -F git-slug=$TRAVIS_REPO_SLUG -F git-branch=$TRAVIS_BRANCH -F pylint-report=@/tmp/pylint-report.html http://63.33.197.197:80/pylint-reports
  - curl -v -m 120 -X POST -F git-slug=$TRAVIS_REPO_SLUG -F git-branch=$TRAVIS_BRANCH -F coverage-report=@/tmp/coverage.html http://63.33.197.197:80/coverage-reports
